// generated by go run genicons.go; DO NOT EDIT

package logo

var list = []struct {
	name string
	data []byte
}{
	{"IpfsLogoBottom", IpfsLogoBottom},
	{"IpfsLogoMid", IpfsLogoMid},
	{"IpfsLogoTop", IpfsLogoTop},
}
