package icons

import (
	"gioui.org/widget"
)

func NewIPFSicons() (i map[string]*widget.Icon) {
	i = make(map[string]*widget.Icon)
	//i["logo"] = mustIcon(widget.NewIcon(logo.Wing))
	i["GlyphAdd"] = mustIcon(widget.NewIcon(GlyphAdd))
	i["GlyphAttention"] = mustIcon(widget.NewIcon(GlyphAttention))
	i["GlyphBasket"] = mustIcon(widget.NewIcon(GlyphBasket))
	i["GlyphBook"] = mustIcon(widget.NewIcon(GlyphBook))
	i["GlyphCalendar"] = mustIcon(widget.NewIcon(GlyphCalendar))
	i["GlyphCamera"] = mustIcon(widget.NewIcon(GlyphCamera))
	i["GlyphCancel"] = mustIcon(widget.NewIcon(GlyphCancel))
	i["GlyphCase"] = mustIcon(widget.NewIcon(GlyphCase))
	i["GlyphChart"] = mustIcon(widget.NewIcon(GlyphChart))
	i["GlyphChat"] = mustIcon(widget.NewIcon(GlyphChat))
	i["GlyphClock"] = mustIcon(widget.NewIcon(GlyphClock))
	i["GlyphCloud"] = mustIcon(widget.NewIcon(GlyphCloud))
	i["GlyphCopy"] = mustIcon(widget.NewIcon(GlyphCopy))
	i["GlyphData"] = mustIcon(widget.NewIcon(GlyphData))
	i["GlyphDocCalc"] = mustIcon(widget.NewIcon(GlyphDocCalc))
	i["GlyphDocGeneric"] = mustIcon(widget.NewIcon(GlyphDocGeneric))
	i["GlyphDocMovie"] = mustIcon(widget.NewIcon(GlyphDocMovie))
	i["GlyphDocMusic"] = mustIcon(widget.NewIcon(GlyphDocMusic))
	i["GlyphDocPicture"] = mustIcon(widget.NewIcon(GlyphDocPicture))
	i["GlyphDocText"] = mustIcon(widget.NewIcon(GlyphDocText))
	i["GlyphDocument"] = mustIcon(widget.NewIcon(GlyphDocument))
	i["GlyphDots"] = mustIcon(widget.NewIcon(GlyphDots))
	i["GlyphFilter"] = mustIcon(widget.NewIcon(GlyphFilter))
	i["GlyphFolder"] = mustIcon(widget.NewIcon(GlyphFolder))
	i["GlyphHome"] = mustIcon(widget.NewIcon(GlyphHome))
	i["GlyphIdea"] = mustIcon(widget.NewIcon(GlyphIdea))
	i["GlyphInfo"] = mustIcon(widget.NewIcon(GlyphInfo))
	i["GlyphLab"] = mustIcon(widget.NewIcon(GlyphLab))
	i["GlyphLink"] = mustIcon(widget.NewIcon(GlyphLink))
	i["GlyphLock"] = mustIcon(widget.NewIcon(GlyphLock))
	i["GlyphMail"] = mustIcon(widget.NewIcon(GlyphMail))
	i["GlyphMap"] = mustIcon(widget.NewIcon(GlyphMap))
	i["GlyphMarker"] = mustIcon(widget.NewIcon(GlyphMarker))
	i["GlyphMobile"] = mustIcon(widget.NewIcon(GlyphMobile))
	i["GlyphMonitor"] = mustIcon(widget.NewIcon(GlyphMonitor))
	//i["GlyphNewFolder"] = mustIcon(widget.NewIcon(GlyphNewFolder))
	i["GlyphPeersLarge"] = mustIcon(widget.NewIcon(GlyphPeersLarge))
	i["GlyphPeersMedium"] = mustIcon(widget.NewIcon(GlyphPeersMedium))
	i["GlyphPeersSmall"] = mustIcon(widget.NewIcon(GlyphPeersSmall))
	i["GlyphPencil"] = mustIcon(widget.NewIcon(GlyphPencil))
	i["GlyphPin"] = mustIcon(widget.NewIcon(GlyphPin))
	i["GlyphPower"] = mustIcon(widget.NewIcon(GlyphPower))
	i["GlyphSearch"] = mustIcon(widget.NewIcon(GlyphSearch))
	i["GlyphServer"] = mustIcon(widget.NewIcon(GlyphServer))
	i["GlyphSettings"] = mustIcon(widget.NewIcon(GlyphSettings))
	i["GlyphShare"] = mustIcon(widget.NewIcon(GlyphShare))
	i["GlyphSmallArrow"] = mustIcon(widget.NewIcon(GlyphSmallArrow))
	i["GlyphSmallCancel"] = mustIcon(widget.NewIcon(GlyphSmallCancel))
	i["GlyphSmallInfo"] = mustIcon(widget.NewIcon(GlyphSmallInfo))
	i["GlyphSmallTick"] = mustIcon(widget.NewIcon(GlyphSmallTick))
	i["GlyphSpeaker"] = mustIcon(widget.NewIcon(GlyphSpeaker))
	i["GlyphTag"] = mustIcon(widget.NewIcon(GlyphTag))
	i["GlyphTick"] = mustIcon(widget.NewIcon(GlyphTick))
	i["GlyphTrash"] = mustIcon(widget.NewIcon(GlyphTrash))
	i["GlyphUser"] = mustIcon(widget.NewIcon(GlyphUser))
	i["GlyphVoice"] = mustIcon(widget.NewIcon(GlyphVoice))
	i["GlyphWallet"] = mustIcon(widget.NewIcon(GlyphWallet))
	i["GlyphWindow"] = mustIcon(widget.NewIcon(GlyphWindow))
	i["StrokeAttention"] = mustIcon(widget.NewIcon(StrokeAttention))
	i["StrokeBasket"] = mustIcon(widget.NewIcon(StrokeBasket))
	i["StrokeBook"] = mustIcon(widget.NewIcon(StrokeBook))
	i["StrokeCalendar"] = mustIcon(widget.NewIcon(StrokeCalendar))
	i["StrokeCamera"] = mustIcon(widget.NewIcon(StrokeCamera))
	i["StrokeCancel"] = mustIcon(widget.NewIcon(StrokeCancel))
	i["StrokeCase"] = mustIcon(widget.NewIcon(StrokeCase))
	i["StrokeCentralization"] = mustIcon(widget.NewIcon(StrokeCentralization))
	i["StrokeChart"] = mustIcon(widget.NewIcon(StrokeChart))
	i["StrokeChat"] = mustIcon(widget.NewIcon(StrokeChat))
	i["StrokeClock"] = mustIcon(widget.NewIcon(StrokeClock))
	i["StrokeCloud"] = mustIcon(widget.NewIcon(StrokeCloud))
	i["StrokeCode"] = mustIcon(widget.NewIcon(StrokeCode))
	i["StrokeCopy"] = mustIcon(widget.NewIcon(StrokeCopy))
	i["StrokeCube"] = mustIcon(widget.NewIcon(StrokeCube))
	i["StrokeData"] = mustIcon(widget.NewIcon(StrokeData))
	i["StrokeDecentralization"] = mustIcon(widget.NewIcon(StrokeDecentralization))
	i["StrokeDevices"] = mustIcon(widget.NewIcon(StrokeDevices))
	i["StrokeDistributed"] = mustIcon(widget.NewIcon(StrokeDistributed))
	i["StrokeDocument"] = mustIcon(widget.NewIcon(StrokeDocument))
	i["StrokeDownload"] = mustIcon(widget.NewIcon(StrokeDownload))
	i["StrokeFilter"] = mustIcon(widget.NewIcon(StrokeFilter))
	i["StrokeFolder"] = mustIcon(widget.NewIcon(StrokeFolder))
	i["StrokeIdea"] = mustIcon(widget.NewIcon(StrokeIdea))
	i["StrokeInfo"] = mustIcon(widget.NewIcon(StrokeInfo))
	i["StrokeIpld"] = mustIcon(widget.NewIcon(StrokeIpld))
	i["StrokeLab"] = mustIcon(widget.NewIcon(StrokeLab))
	i["StrokeLock"] = mustIcon(widget.NewIcon(StrokeLock))
	i["StrokeMail"] = mustIcon(widget.NewIcon(StrokeMail))
	i["StrokeMap"] = mustIcon(widget.NewIcon(StrokeMap))
	i["StrokeMarker"] = mustIcon(widget.NewIcon(StrokeMarker))
	i["StrokeMarketing"] = mustIcon(widget.NewIcon(StrokeMarketing))
	i["StrokeMobile"] = mustIcon(widget.NewIcon(StrokeMobile))
	i["StrokeMonitor"] = mustIcon(widget.NewIcon(StrokeMonitor))
	i["StrokeNewFolder"] = mustIcon(widget.NewIcon(StrokeNewFolder))
	i["StrokePen"] = mustIcon(widget.NewIcon(StrokePen))
	i["StrokePencil"] = mustIcon(widget.NewIcon(StrokePencil))
	i["StrokePicture"] = mustIcon(widget.NewIcon(StrokePicture))
	i["StrokePin"] = mustIcon(widget.NewIcon(StrokePin))
	i["StrokePresentation"] = mustIcon(widget.NewIcon(StrokePresentation))
	i["StrokeSearch"] = mustIcon(widget.NewIcon(StrokeSearch))
	i["StrokeServer"] = mustIcon(widget.NewIcon(StrokeServer))
	i["StrokeSettings"] = mustIcon(widget.NewIcon(StrokeSettings))
	i["StrokeShare"] = mustIcon(widget.NewIcon(StrokeShare))
	i["StrokeSpeaker"] = mustIcon(widget.NewIcon(StrokeSpeaker))
	i["StrokeTag"] = mustIcon(widget.NewIcon(StrokeTag))
	i["StrokeTick"] = mustIcon(widget.NewIcon(StrokeTick))
	i["StrokeTrash"] = mustIcon(widget.NewIcon(StrokeTrash))
	i["StrokeUser"] = mustIcon(widget.NewIcon(StrokeUser))
	i["StrokeVoice"] = mustIcon(widget.NewIcon(StrokeVoice))
	i["StrokeWallet"] = mustIcon(widget.NewIcon(StrokeWallet))
	i["StrokeWeb"] = mustIcon(widget.NewIcon(StrokeWeb))
	i["StrokeWindow"] = mustIcon(widget.NewIcon(StrokeWindow))
	return i
}

func mustIcon(ic *widget.Icon, err error) *widget.Icon {
	if err != nil {
		panic(err)
	}
	return ic
}
